### ISSUE TITLE
Adding mdns command

### ISSUE THREAD

**Issue by JinkeJ** [cocool97/adb_client#36]
Is it possible to implement the mdns command?

**Comment by cocool97** [comment]
It's totally possible yes ! I'm currently working on the USB feature, but I'll look into it afterwards

**Comment by JinkeJ** [comment]
The repository is for your reference: https://github.com/oslo254804746/radb

**Comment by cocool97** [comment]
What is your configuration and your ADB version ? When running `adb mdns services` I receive an error stating that this command is unrecognized..

**Comment by JinkeJ** [comment]
Hi cocool97, the mdns feature needs ADB version 31.0.2 or later, you might want to download the newest version from android sdk

**Comment by cocool97** [comment]
I've got version 35.0.1 from fedora repositories, can't figure out why I don't have this command

**Comment by cocool97** [comment]
Already tried it, just re-tried to be sure I properly restarted adb server but does not improve. I'll check it more

**Comment by cocool97** [comment]
@JinkeJ I just pushed a `mdns` branch (and a PR) to let you try an implementation. mdns is hidden behing a `mdns`  feature. 

A thread is spawned and get a `Sender` as a parameter to send device information when new devices are detected. Currently device fullname and IP adresses are returned, can add more depending on your needs !

**Comment by JinkeJ** [comment]
Great! Let me try it.

**Comment by cocool97** [comment]
I do not use ADB server to search for mdns devices, I use a rust crate doing all the work. Prefix is yet indeed limited, have you tried changing the prefix ? It should be only `_adb._tcp` for you but doesn't work for me

**Comment by JinkeJ** [comment]
Yes, All of them are tried including empty prefix. I don't know why it does not work on my computer, I guess it is better to implement it through adb server.

**Comment by cocool97** [comment]
Implementing it through the ADB server would prevent users with low adb versions to access this feature. That's why I implemented it using pure Rust.

Are you using the CLI or the crate ? Is it working on ADB server at the same time ?

**Comment by JinkeJ** [comment]
I think we can check the adb server version before issuing mdns command.

> Are you using the CLI or the crate ? Is it working on ADB server at the same time ?
I'm using the crate, the adb server is working well, only the mdns feature didn't give any response, I even exported the event of mdns::Found.

**Comment by cocool97** [comment]
Implementing it through the ADB server would prevent users with low adb versions to access this feature. That's why I implemented it using pure Rust.

Are you using the CLI or the crate ? Is it working on ADB server at the same time ?

**Comment by cocool97** [comment]
That's not even an issue of checking whether the server supports it, that's rather offering this feature to all users without having to use the server. 

I'm kinda confused about it, what devices are you testing it on ?

**Comment by JinkeJ** [comment]
I'm just using my mobile phone. The mdns feature let me know whether my phone is ready to be connected in local network.

**Comment by cocool97** [comment]
Ok, I see..
Can you implement the mdns part using adb-server ?

**Comment by JinkeJ** [comment]
OK😬

**Comment by JinkeJ** [comment]
@cocool97 #55
