### ISSUE TITLE
adb connection refused (os error 111).

### ISSUE THREAD

**Issue by lidgnulinux** [cocool97/adb_client#41]
Hello, I'm trying this tool on musl-based distro. When I run :

```
$ adb_client devices
```

I always get `adb connection refused (os error 111)`. There is complain about not able to start adb server or something.
I can't post the detail outputs since I'm away from my laptop.

**Comment by lidgnulinux** [comment]
Hello, thanks for the response.

> Do you have adb available in $PATH ?

Sadly, no. I thought adb_client is alternative to adb itself.

**Comment by cocool97** [comment]
Work is in progress in the `usb` branch ! Feature will come in the next few weeks :)
