### ISSUE TITLE
AdbStatResponse is not (sufficiently) pub

### ISSUE THREAD

**Issue by evanrichter** [cocool97/adb_client#57]
Hi, thanks for the awesome crate! It's working wonderfully to automate tests with hardware over adb.

I would like to implement `ADBDeviceExt` for an enum of either ADBUsbDevice or ADBServerDevice, so I can interact with a device using either protocol, but it's not possible for 3rd parties to impl ADBDeviceExt because AdbStatResponse is not reachable through public modules or a `pub use` export.

**Comment by evanrichter** [comment]
Yep, that's the only one

You can tell quickly by looking at the docs for [ADBDeviceExt](https://docs.rs/adb_client/latest/adb_client/trait.ADBDeviceExt.html) and noticing that AdbStatResponse is the only type or generic that isn't clickable

**Comment by cocool97** [comment]
Fix available in v2.0.4 !

**Comment by evanrichter** [comment]
🔥 thanks!
