### ISSUE TITLE
How to connect two devices of the same model using USB? thank you

### ISSUE THREAD

**Issue by LoneMK** [cocool97/adb_client#65]
The vendor_id and product_id of the two devices are the same

**Comment by LoneMK** [comment]
Look forward to realizing the problem I've described

**Comment by cocool97** [comment]
@LoneMK Can you test related PR ?

A new constructor has been added to `ADBUSBDevice`, taking as a parameter an `USBTransport` that can be created from a `rusb::Device`. 

This is the more flexible solution imho as the caller can get the desired device with more flexibility.

Let me know if this fixes your issue 😃

**Comment by LoneMK** [comment]
Ok, I'll try

**Comment by LoneMK** [comment]
It looks okay

**Comment by LoneMK** [comment]
I've solved my problem. Thank you

**Comment by cocool97** [comment]
Ok, I'll merge it then
