### ISSUE TITLE
Does this library require adb executable files to work?

### ISSUE THREAD

**Issue by pavi2410** [cocool97/adb_client#75]
https://github.com/cocool97/adb_client/blob/9002ecc0c8e621339731164ad24891d253e61f91/adb_client/src/server/adb_server.rs#L56

README says "Full Rust, don't use adb * shell commands to interact with devices", However, looking at the source, I am so confused whether this library requires `adb` executable file on the PATH or not. It would be awesome to use it without the `adb` executables for each platform.

Use case: I am building a Tauri GUI app that requires the use of ADB to connect to the users device via USB or Wifi. I found this library in hopes that this doesn't require the official `adb` executable files provided by Google to installed in the PATH to work. The other choice would be to embed the official executables.

**Comment by pavi2410** [comment]
Related: https://github.com/cocool97/adb_client/issues/41

**Comment by cocool97** [comment]
Hey !

This library has 2 main features:

- Using ADB server as a bridge (by using `ADBServerDevice` structure). It uses ADB protocol to communicate with the server, but it has to be started (and therefore be in the PATH)
- Using `ADBUSBDevice` or `ADBTcpDevice` structures, that interact directly with end devices without needing an ADB server. 

The second option is likely what you need to build your project :) 

Let me know if there is anything I can do to help, I'm interested in knowing how easy this library is easy to understand / use !

**Comment by cocool97** [comment]
Hey !

This library has 2 main features:

- Using ADB server as a bridge (by using `ADBServerDevice` structure). It uses ADB protocol to communicate with the server, but it has to be started (and therefore be in the PATH)
- Using `ADBUSBDevice` or `ADBTcpDevice` structures, that interact directly with end devices without needing an ADB server. 

The second option is likely what you need to build your project :) 

Let me know if there is anything I can do to help, I'm interested in knowing how easy this library is easy to understand / use !

**Comment by cocool97** [comment]
This library should provide you with everything you need :) 

What kind of commands would you need ? Like execute / push / pull files ? Could this GUI be added into current project to help users manage their android devices with UI ?

The only thing that might be missing is device discovery. Currently mdns is implemented for TCP devices, and there is also a private function in the library that filters USB connected  devices !

**Comment by pavi2410** [comment]
I can contribute such a GUI for this project separately.

The existing solution that we have was written using V lang and I am wanting to migrate to Rust :) See https://github.com/Kodular/Starter

**Comment by cocool97** [comment]
Looking forward to seeing this new project, let me know if you encounter any bugs !

**Comment by pavi2410** [comment]
Thanks @cocool97! This is working great!!!

```rs
    let mut usb_device = ADBUSBDevice::autodetect().unwrap();

    // get a std::io::Write
    let mut serial_no: Vec<u8> = Vec::new();
    let mut model: Vec<u8> = Vec::new();
    let mut release: Vec<u8> = Vec::new();
    let mut sdk_version: Vec<u8> = Vec::new();

    usb_device
        .shell_command(["getprop", "ro.serialno"], &mut serial_no)
        .unwrap();

    usb_device
        .shell_command(["getprop", "ro.product.model"], &mut model)
        .unwrap();

    usb_device
        .shell_command(["getprop", "ro.build.version.release"], &mut release)
        .unwrap();

    usb_device
        .shell_command(["getprop", "ro.build.version.sdk"], &mut sdk_version)
        .unwrap();

    println!("Serial No: {:?}", from_utf8(serial_no.as_slice()));
    println!("Model: {:?}", from_utf8(model.as_slice()));
    println!("Release: {:?}", from_utf8(release.as_slice()));
    println!("SDK Version: {:?}", from_utf8(sdk_version.as_slice()));
```

![image](https://github.com/user-attachments/assets/ff79f891-d656-4670-9797-d22bd3ac5457)

**Comment by cocool97** [comment]
Happy to see it works ! 🫡

**Comment by pavi2410** [comment]
I just don't believe how it was using this library!

![image](https://github.com/user-attachments/assets/0818d208-9e9b-4295-bf26-4eb6b785d935)
