### ISSUE TITLE
type-state API?

### ISSUE THREAD

**Issue by Rudxain** [cocool97/adb_client#76]
Something like [this](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/blob/30359cb6848bec39257ca9e8593c87f7a68137ed/src/core/sync.rs#L64-L202) ([PR](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/pull/757))

Although the lib already has a method-based API, which seems good enough! Feel free to close this if this proposal would add too much duplicate APIs (assuming you want to avoid increasing the major sem-ver number)

**Comment by cocool97** [comment]
Hey ! 

This is not planned, as this would require a total refactoring of the current API or maintaining 2 times more code. The current API design shouldn't be an issue to implement quite of everything you point in the PR :)
